name: CI/CD Pipeline

# Kích hoạt workflow khi có push hoặc pull request vào nhánh main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code từ repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Cài đặt Python (nếu bạn cần cài đặt và chạy test)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Cài đặt dependencies (nếu cần cho việc test)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r exam-generator/requirements.txt

      # 4. Chạy test (nếu bạn có bài test, ví dụ dùng pytest)
      - name: Run tests
        run: |
          # Giả sử bạn có thư mục tests hoặc test file trong exam-generator
          pytest exam-generator/tests

      # 5. Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t duyhung020304/exam-generator:${{ github.sha }} exam-generator

      # 6. Đăng nhập Docker Hub (dùng GitHub Secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 7. Push Docker image lên Docker Hub
      - name: Push Docker Image
        run: |
          docker push duyhung020304/exam-generator:${{ github.sha }}
