name: Deploy PHP to Azure

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "duyhung"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

